-- H2-compatible schema for testing (PostgreSQL mode)

CREATE TABLE IF NOT EXISTS tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(255) UNIQUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    phone_number VARCHAR(255) UNIQUE,
    email_verified_at TIMESTAMP,
    password VARCHAR(255),
    account_number VARCHAR(10),
    fcm_token VARCHAR(255),
    type VARCHAR(255) DEFAULT 'user',
    tier_id BIGINT,
    parent_id BIGINT,
    onboarding_id BIGINT,
    platform VARCHAR(255),
    app_version VARCHAR(255),
    pnd BOOLEAN DEFAULT FALSE,
    bvn VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    middle_name VARCHAR(255),
    gender VARCHAR(255),
    date_of_birth DATE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS privileges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(255) UNIQUE,
    description TEXT,
    modules VARCHAR(1000),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(255) UNIQUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_privilege (
    role_id BIGINT NOT NULL,
    privilege_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, privilege_id)
);

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    phone_number VARCHAR(255),
    password VARCHAR(255),
    blocked_at TIMESTAMP,
    blocked_reason VARCHAR(255),
    email_verified_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_role (
    admin_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (admin_id, role_id)
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(255) UNIQUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    code VARCHAR(255) UNIQUE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    code VARCHAR(255) UNIQUE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    code VARCHAR(255) UNIQUE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(255),
    context VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(26),
    user_id BIGINT,
    product_id BIGINT,
    provider_id BIGINT,
    channel_id BIGINT,
    outlet_id BIGINT,
    device_id BIGINT,
    payment_method_id BIGINT,
    status_code VARCHAR(255),
    status_message VARCHAR(500),
    provider_code VARCHAR(255),
    channel VARCHAR(255),
    payment_method VARCHAR(255),
    service_fee DECIMAL(15,2) DEFAULT 0,
    agent_commission DECIMAL(15,2) DEFAULT 0,
    aggregator_commission DECIMAL(15,2) DEFAULT 0,
    company_commission DECIMAL(15,2) DEFAULT 0,
    amount_to_pay DECIMAL(15,2) DEFAULT 0,
    retry_count INT DEFAULT 0,
    amount DECIMAL(15,2),
    transactable_type VARCHAR(255),
    transactable_id BIGINT,
    terminal_id VARCHAR(255),
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    walletable_type VARCHAR(255),
    walletable_id BIGINT,
    type VARCHAR(255) DEFAULT 'default',
    balance DECIMAL(15,2) DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS statements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT,
    category VARCHAR(255),
    source_type VARCHAR(255),
    source_id BIGINT,
    source_reference VARCHAR(255),
    description VARCHAR(255),
    amount DECIMAL(15,2),
    previous_balance DECIMAL(15,2) DEFAULT 0,
    current_balance DECIMAL(15,2) DEFAULT 0,
    type VARCHAR(255),
    reversal BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ledgers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255),
    sub_category VARCHAR(255),
    code VARCHAR(255),
    name VARCHAR(255),
    description VARCHAR(1000),
    balance DECIMAL(15,2) DEFAULT 0,
    on_credit VARCHAR(255),
    on_debit VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contra BOOLEAN DEFAULT FALSE,
    transaction_type VARCHAR(255),
    transaction_id BIGINT,
    ledger_id BIGINT,
    ledger_account_id BIGINT,
    debit DECIMAL(15,2) DEFAULT 0,
    credit DECIMAL(15,2) DEFAULT 0,
    previous_balance DECIMAL(15,2) DEFAULT 0,
    current_balance DECIMAL(15,2) DEFAULT 0,
    description VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255),
    description VARCHAR(1000),
    admin_id BIGINT,
    actionable_type VARCHAR(255),
    actionable_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ledger_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255),
    sub_category VARCHAR(255),
    code VARCHAR(255),
    name VARCHAR(255),
    description VARCHAR(1000),
    balance DECIMAL(15,2) DEFAULT 0,
    on_credit VARCHAR(255),
    on_debit VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module VARCHAR(255),
    type VARCHAR(255),
    value VARCHAR(255),
    expression VARCHAR(1000),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ingress_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(255),
    scheme VARCHAR(50),
    method VARCHAR(10),
    controller VARCHAR(255),
    action VARCHAR(255),
    ip VARCHAR(50),
    ips VARCHAR(255),
    url VARCHAR(1000),
    user_agent VARCHAR(500),
    header TEXT,
    data TEXT,
    body TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS virtual_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    account_name VARCHAR(255),
    account_number VARCHAR(50),
    bank_name VARCHAR(255),
    bank_code VARCHAR(20),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS nins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    number VARCHAR(255),
    first_name VARCHAR(255),
    middle_name VARCHAR(255),
    last_name VARCHAR(255),
    phone_number VARCHAR(255),
    email VARCHAR(255),
    gender VARCHAR(50),
    date_of_birth DATE,
    status_code VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(10),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(10),
    country_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    addressable_type VARCHAR(255),
    addressable_id BIGINT,
    address TEXT,
    lga VARCHAR(255),
    state_id BIGINT,
    country_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(255),
    url VARCHAR(1000),
    method VARCHAR(10),
    header TEXT,
    body TEXT,
    data TEXT,
    provider_id BIGINT,
    source_ip VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pipelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(255),
    sequence INT,
    name VARCHAR(255),
    description TEXT,
    pipe VARCHAR(255),
    error TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS iso_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    reference VARCHAR(255),
    class VARCHAR(255),
    mti VARCHAR(10),
    fields TEXT,
    iso TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
